name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install || true
          else
            echo "No package.json found."
          fi

      - name: Run the bot
        run: |
          if [ -f index.js ]; then
            node index.js
          else
            echo "No index.js found to run"
          fi
