name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]  # choose what you need

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Install dependencies
        run: npm ci  # or npm install

      - name: Run tests / build
        run: npm test  # or your custom command (e.g., node index.js)
