name: ci

on:
  schedule:
    - cron: "*/15 * * * *" # Every 15 minutes (you can adjust this)
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node index.js
